services:
  - type: web
    name: marwen-server
    runtime: node
    plan: starter
    buildCommand: npm install --no-audit --no-fund
    startCommand: npm run server
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
}
